[tool.black]
line-length = 100
target-version = ["py311"]
skip-string-normalization = true

[tool.isort]
profile = "black"
line_length = 100
known_first_party = ["tools", "exercises"]
skip = ["venv", ".venv", "reports", "pdf_report_weekly"]

[tool.ruff]
line-length = 100
target-version = "py311"
extend-select = ["E", "F", "W", "I", "D", "UP", "ANN", "S"]
ignore = ["D203", "D213"]
exclude = ["venv", ".venv", "tools/rules", "reports", "pdf_report_weekly", "__pycache__"]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.mypy]
ignore_missing_imports = true
disallow_untyped_defs = false
show_error_codes = true
python_version = "3.11"
